CPPFLAGS=-std=gnu++98 -pedantic -Wall -Werror -ggdb3
cyoa-step2: cyoa-step2.cpp story.hpp story.cpp page.hpp page.cpp
	g++ $(CPPFLAGS) -o cyoa-step2 cyoa-step2.cpp story.hpp story.cpp page.hpp page.cpp
